-- ARGUS+ player profiles and campaign scores for the username/password MVP.
-- Run this once in Supabase SQL Editor for project tshojzkaojcehjunhbju.

create table if not exists public.player_profiles (
  id uuid primary key,
  name text not null check (char_length(name) between 2 and 20),
  avatar text not null default '/assets/lawyer-cat-transparent.png',
  total_score integer not null default 0 check (total_score >= 0),
  completed_levels integer not null default 0 check (completed_levels >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safe upgrade path if an earlier prototype table already exists.
alter table public.player_profiles
  add column if not exists avatar text not null default '/assets/lawyer-cat-transparent.png';

create table if not exists public.campaign_runs (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.player_profiles(id) on delete cascade,
  level_id integer not null check (level_id between 1 and 99),
  score integer not null default 0 check (score >= 0),
  outcome text not null check (outcome in ('player_win', 'opponent_win')),
  created_at timestamptz not null default now()
);

create or replace view public.leaderboard as
select id, name, avatar, total_score, completed_levels
from public.player_profiles;

create index if not exists campaign_runs_player_created_idx
  on public.campaign_runs (player_id, created_at desc);
create index if not exists player_profiles_score_idx
  on public.player_profiles (total_score desc, completed_levels desc);
create unique index if not exists player_profiles_name_unique_idx
  on public.player_profiles (lower(name));

alter table public.player_profiles enable row level security;
alter table public.campaign_runs enable row level security;

drop policy if exists "public can read profiles" on public.player_profiles;
create policy "public can read profiles"
  on public.player_profiles for select using (true);

drop policy if exists "public can create profiles" on public.player_profiles;
drop policy if exists "users can create own profiles" on public.player_profiles;
create policy "users can create own profiles"
  on public.player_profiles for insert to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "public can update profiles" on public.player_profiles;
drop policy if exists "users can update own profiles" on public.player_profiles;
create policy "users can update own profiles"
  on public.player_profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "public can create runs" on public.campaign_runs;
drop policy if exists "users can create own runs" on public.campaign_runs;
create policy "users can create own runs"
  on public.campaign_runs for insert to authenticated
  with check ((select auth.uid()) = player_id);

drop policy if exists "public can read runs" on public.campaign_runs;
drop policy if exists "users can read own runs" on public.campaign_runs;
create policy "users can read own runs"
  on public.campaign_runs for select to authenticated
  using ((select auth.uid()) = player_id);

grant select on public.leaderboard to anon, authenticated;
grant select on public.player_profiles to anon, authenticated;
grant insert, update on public.player_profiles to authenticated;
grant insert, select on public.campaign_runs to authenticated;
grant usage, select on sequence public.campaign_runs_id_seq to authenticated;

-- Remove broad grants left by the first prototype migration.
revoke insert, update on public.player_profiles from anon;
revoke insert, select on public.campaign_runs from anon;
revoke usage, select on sequence public.campaign_runs_id_seq from anon;

create or replace function public.touch_player_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists player_profiles_updated_at on public.player_profiles;
create trigger player_profiles_updated_at
before update on public.player_profiles
for each row execute function public.touch_player_profile_updated_at();
