-- ARGUS+ player profiles and campaign scores for the username/password MVP.
-- Run in your Supabase SQL Editor. Re-runnable; no existing scores are deleted.
begin;

create table if not exists public.player_profiles (
  id uuid primary key,
  name text not null check (char_length(name) between 2 and 20),
  avatar text not null default '/assets/lawyer-cat-transparent.png',
  total_score integer not null default 0 check (total_score >= 0),
  completed_levels integer not null default 0 check (completed_levels >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safe upgrade path if an earlier prototype table already exists.
alter table public.player_profiles
  add column if not exists avatar text not null default '/assets/lawyer-cat-transparent.png';

create table if not exists public.campaign_runs (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.player_profiles(id) on delete cascade,
  level_id integer not null check (level_id between 1 and 99),
  score integer not null default 0 check (score >= 0),
  outcome text not null check (outcome in ('player_win', 'opponent_win')),
  created_at timestamptz not null default now()
);

create or replace view public.leaderboard as
select id, name, avatar, total_score, completed_levels
from public.player_profiles;

create index if not exists campaign_runs_player_created_idx
  on public.campaign_runs (player_id, created_at desc);
-- Existing prototypes may contain repeated wins. Serialize new settlements by
-- locking the profile instead of adding an index that would reject old data.
create index if not exists player_profiles_score_idx
  on public.player_profiles (total_score desc, completed_levels desc);
create unique index if not exists player_profiles_name_unique_idx
  on public.player_profiles (lower(name));

alter table public.player_profiles enable row level security;
alter table public.campaign_runs enable row level security;

drop policy if exists "public can read profiles" on public.player_profiles;

drop policy if exists "public can create profiles" on public.player_profiles;
drop policy if exists "users can create own profiles" on public.player_profiles;

drop policy if exists "public can update profiles" on public.player_profiles;
drop policy if exists "users can update own profiles" on public.player_profiles;

drop policy if exists "public can create runs" on public.campaign_runs;
drop policy if exists "users can create own runs" on public.campaign_runs;

drop policy if exists "public can read runs" on public.campaign_runs;
drop policy if exists "users can read own runs" on public.campaign_runs;

revoke all on public.player_profiles from public, anon, authenticated;
-- This is an updatable definer view. Supabase default grants may include writes.
revoke all on public.leaderboard from public, anon, authenticated;
grant select on public.leaderboard to anon, authenticated;

-- Remove broad grants left by the first prototype migration.
revoke all on public.campaign_runs from public, anon, authenticated;
revoke all on sequence public.campaign_runs_id_seq from public, anon, authenticated;
grant select, insert, update on public.player_profiles to service_role;
grant select, insert on public.campaign_runs to service_role;
grant usage, select on sequence public.campaign_runs_id_seq to service_role;
grant select on public.leaderboard to service_role;

create or replace function public.is_username_available(p_name text, p_email text)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select not exists (select 1 from public.player_profiles where lower(name) = lower(p_name))
     and not exists (select 1 from auth.users where lower(email) = lower(p_email));
$$;
revoke execute on function public.is_username_available(text, text) from public, anon, authenticated;
grant execute on function public.is_username_available(text, text) to service_role;

create or replace function public.save_player_profile(p_player_id uuid, p_name text, p_avatar text default null)
returns public.player_profiles
language plpgsql security definer set search_path = ''
as $$
declare result public.player_profiles;
begin
  if not exists (select 1 from auth.users where id = p_player_id) then
    raise exception using errcode = '23503', message = 'auth user not found';
  end if;
  -- Initialization always starts at zero. Updating an avatar never reads or
  -- writes totals, and cannot overwrite a concurrently settled win or a name.
  insert into public.player_profiles(id, name, avatar)
  values (p_player_id, p_name, coalesce(p_avatar, '/assets/lawyer-cat-transparent.png'))
  on conflict (id) do update
    set avatar = coalesce(p_avatar, player_profiles.avatar)
  returning * into result;
  return result;
end;
$$;
revoke execute on function public.save_player_profile(uuid, text, text) from public, anon, authenticated;
grant execute on function public.save_player_profile(uuid, text, text) to service_role;

create or replace function public.record_campaign_win(p_player_id uuid, p_level_id integer, p_score integer)
returns public.player_profiles
language plpgsql
security definer
set search_path = ''
as $$
declare result public.player_profiles;
begin
  if p_score is null or p_score <> 88 or p_level_id is null or p_level_id < 1 or p_level_id > 20 then
    raise exception 'invalid campaign result';
  end if;
  select * into result from public.player_profiles where id = p_player_id for update;
  if result.id is null then
    raise exception using errcode = '23503', message = 'player profile not found';
  end if;
  -- Retries (including lost HTTP responses) and concurrent requests award once.
  if exists (select 1 from public.campaign_runs
             where player_id = p_player_id and level_id = p_level_id and outcome = 'player_win') then
    return result;
  end if;
  insert into public.campaign_runs(player_id, level_id, score, outcome)
  values (p_player_id, p_level_id, p_score, 'player_win');
  update public.player_profiles
    set total_score = total_score + p_score,
        completed_levels = completed_levels + 1
    where id = p_player_id
    returning * into result;
  return result;
end;
$$;

revoke execute on function public.record_campaign_win(uuid, integer, integer) from public, anon, authenticated;
grant execute on function public.record_campaign_win(uuid, integer, integer) to service_role;

create or replace function public.touch_player_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists player_profiles_updated_at on public.player_profiles;
create trigger player_profiles_updated_at
before update on public.player_profiles
for each row execute function public.touch_player_profile_updated_at();

commit;
