import { createContext, useContext } from 'react';

export type Locale = 'zh' | 'en';

export const LOCALE_STORAGE_KEY = 'argus-locale';

export function normalizeLocale(value: string | null | undefined): Locale {
  return value === 'en' ? 'en' : 'zh';
}

export function detectLocale(preferred?: string | null): Locale {
  if (preferred) return normalizeLocale(preferred);
  if (typeof navigator !== 'undefined') return normalizeLocale(navigator.language?.toLowerCase().startsWith('en') ? 'en' : 'zh');
  return 'zh';
}

export type LocaleContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
};

export const LocaleContext = createContext<LocaleContextValue | null>(null);

export function useLocale() {
  const value = useContext(LocaleContext);
  if (!value) {
    return { locale: 'zh' as Locale, setLocale: () => undefined };
  }
  return value;
}

export function interpolate(text: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), text);
}

export function stripCampaignPrefix(text: string) {
  return text.replace(/^EAZO\s*(?:导入|import)?\s*[·•:\-]?\s*/i, '').trim();
}

export const APP_COPY = {
  zh: {
    brandTitle: '你的证词有猫饼',
    brandSubtitle: 'Meow Court',
    brandAlt: 'Meow Court 律师猫',
    skipLink: '跳到主要内容',
    login: '登录 / 注册',
    loginHint: '用户名 + 密码',
    editProfile: '已登录 · 点击编辑头像',
    logout: '退出',
    localeZh: '中文',
    localeEn: 'EN',
    campaignTitle: '法庭闯关',
    campaignSubtitle: '证据 → 卡牌 → 裁决',
    campaignLead: '先在案发现场搜证，再把证据编成卡牌连击。20 个独立案件，由押金纠纷逐步进阶到综合审判。',
    campaignTag: '搜证 + 庭审',
    campaignOpen: '全部 {count} 关开放',
    campaignProgress: '本次完成 {done}/{total}',
    campaignLoadingMap: '正在载入关卡地图…',
    campaignLoadingCase: '正在载入本关案件…',
    campaignBack: '返回关卡地图',
    campaignRulesTitle: '闯关目标',
    campaignRulesBody: '阅读本关案情与争议焦点 · 自由查看并收集关键原件，然后选择最有利于自己的证据卡牌进入庭审，并出牌、回应质疑并请求裁决',
    campaignLevelBadge: '本关目标',
    campaignStart: '开始搜证 →',
    campaignFocusLabel: '争议焦点',
    campaignInvestigate: '搜证',
    campaignCourt: '庭审',
    campaignVerdict: '裁决',
    campaignSearchTitle: '现场搜证',
    campaignSearchBadge: '自由搜证',
    campaignSearchLog: '搜证日志',
    campaignSourceTitle: '原始文件 · 与当前材料同组',
    campaignSourceReader: '具体租房材料',
    campaignSourceBadge: '原始材料',
    campaignEvidenceTitle: '证据卡组',
    campaignEvidenceBadge: '已选 {selected}/{total}',
    campaignEnterCourt: '带着 {count} 张证据卡进入法庭 →',
    campaignChooseEvidence: '请选择证据卡 →',
    campaignInvestigateHint: '点击左侧现场热点，或在材料中点击线索，收集到的证据会出现在这里。',
    campaignCourtEntryHint: '最多选择 {total} 张证据卡，根据证据内容和重要性做取舍。选择几张，庭审就使用几种证据牌；护盾和回体力战术牌始终可用。',
    campaignCourtRule: '恢复和护盾都靠战术牌；护盾会优先吸收反击伤害。无牌可出时，补牌优先提供可用牌。',
    campaignDifficulty: '难度',
    campaignKeyEvidenceCount: '份关键证据',
    campaignCollected: '已取证',
    campaignKeyEvidence: '关键证据',
    campaignScore: '总分',
    campaignReturnRetry: '返回搜证重试',
    campaignVictory: '我方胜利！',
    campaignDefeat: '对方胜利',
    campaignRequestVerdict: '请求法官裁决',
    campaignVerdictReady: '对方血量归零后可请求裁决',
    campaignNext: '下一关 →',
    campaignFound: '发现证据',
    campaignRemoved: '取消证据',
    campaignRemovedFromTrial: '取消带庭选择',
    campaignNewEvidence: '新证据',
    campaignEvidenceFallback: '证据',
    campaignExplore: '自由调查',
    campaignCollectedMark: '已收集 ✓',
    campaignOpenOriginal: '打开完整原件 →',
    campaignSelectedRemove: '✓ 已选入庭 · 点击取消选择',
    campaignSelectTrial: '点击选择带上庭',
    campaignLevel: '第',
    campaignLevelEn: 'Level',
    campaignDifficultyInline: '· 难度',
    campaignScoreLabel: '总分',
    courtOpponentHp: '对方血量',
    courtPlayerHp: '我方血量',
    courtStamina: '体力',
    courtShield: '护盾',
    courtRound: '庭审回合',
    courtWaiting: '等待对方回应',
    courtTurnPlayer: '轮到我方出牌',
    courtTurnOpponent: '对方反击',
    courtTurnPreparing: '对方准备反击…',
    courtTurnEnd: '本轮已结束',
    courtReturnMap: '← 返回关卡地图',
    courtInvestigate: '搜证',
    courtTrial: '卡牌庭审',
    courtVerdict: '裁决',
    courtOurSide: '我方',
    courtTheirSide: '对方',
    courtEvidencePlay: '证据牌',
    courtRecoveryPlay: '恢复牌',
    courtDefensePlay: '防御牌',
    courtCost: '消耗 {cost} 体力',
    courtEffect: '效果：',
    courtSeconds: '秒',
    courtHand: '手牌 {count}/{total} · 出牌后随机补一张',
    courtPlayed: '已出 {count} 张 · 体力 {stamina}/{max}',
    courtShieldAria: '护盾 {current}/{max}',
    courtEvidenceAccuracy: '可信度 {score}/10',
    courtBattleFeedback: '正在等待庭审反馈…',
    courtVerdictLocked: '对方血量归零后可请求裁决',
    courtEvidenceKey: '关键证据',
    courtEvidenceSupport: '补充证据',
    courtAction: '战术行动 · 不作为裁决证据',
    courtPlayHint: '点击出牌 · 扣除体力并攻击',
    courtRecoveryHint: '使用后恢复体力 · 对方仍会反击',
    courtDefenseHint: '使用后获得护盾 · 对方仍会反击',
    courtRecoveryFull: '体力已满 · 暂不可用',
    courtShieldFull: '护盾已满 · 暂不可用',
    courtLowStamina: '体力不足 · 还需 {cost} 点',
    courtBattleResultWin: '对方血量先归零，证据链压制成功。现在可以请求法官裁决。',
    courtBattleResultLoss: '我方血量先归零。本局最终裁决将按游戏结果作出，证据链仅用于展示本局过程。',
    courtBattleOver: '本轮已结束',
    courtJudgePrompt: '法官提示：',
    courtOpponentReply: '对方回应',
    courtPlayerStatement: '我方陈词',
    courtOpponentReplyPending: '对方正在组织回应…',
    courtNoDebate: '先看体力，再选择证据出牌。 出牌后随机补一张，体力不足时使用恢复牌。',
    courtEvidenceChain: '证据链',
    courtLegalLeads: '法律检索线索',
    courtReady: '关键证据链已闭合，可以请求训练裁决。',
    briefTitle: '本关目标',
    briefStart: '开始搜证 →',
    profileTitleNew: '创建玩家档案',
    profileTitleEdit: '编辑玩家档案',
    profileDesc: '只需设置昵称和头像，就可以开始记录闯关成绩。',
    profileNameLabel: '用户名 / 昵称',
    profileNameHelpAuthed: '账号名',
    profileNameHelpRequired: '必填',
    profileAvatarTitle: '选择头像',
    profileAvatarHint: '使用现有猫咪角色',
    profilePrivacy: '用户名用于登录并参与排行榜查重。密码只交给 Supabase Auth，不会写入玩家档案表。',
    profileSave: '保存并开始闯关 →',
    profileLater: '稍后再改',
    profileAuthLink: '注册 / 登录账号（保存跨设备进度）',
    profileClose: '关闭身份卡',
    profileMissingName: '完善玩家档案',
    profileInvalidName: '用户名需为 2-20 位字母、数字、下划线或短横线。',
    profileSaveError: '保存失败，请稍后重试',
    profileSavedLocal: '已保存到本机；配置 Supabase 后会自动同步云端。',
    profileCloudUnavailable: '云端档案暂时不可用，仍可使用本机模式。',
    profileRunSavedLocal: '本局已记录在本机，云端同步将在 Supabase 配置后生效。',
    logoutError: '退出登录失败',
    authTitleRegister: '注册玩家账号',
    authTitleLogin: '登录玩家账号',
    authDesc: '用户名就是你的昵称，不需要填写邮箱。',
    authRegister: '注册',
    authLogin: '登录',
    authNameLabel: '用户名 / 昵称',
    authNameHelp: '2-20 位',
    authPasswordLabel: '密码',
    authPasswordHelp: '至少 6 位',
    authConfirmLabel: '确认密码',
    authConfirmHelp: '再次输入',
    authUsernameChecking: '查中…',
    authUsernameAvailable: '可用 ✓',
    authCheck: '查重',
    authSubmitRegister: '注册并开始闯关 →',
    authSubmitLogin: '登录 →',
    authClose: '关闭登录窗口',
    authRegisterMessage: '注册成功，但当前开启了邮箱确认。请在 Supabase Auth → Providers 中关闭 Confirm email 后再登录。',
    authNotConfigured: '当前未配置 Supabase，暂时只能使用本机试玩。',
    authPasswordMismatch: '两次密码输入不一致。',
    authPasswordShort: '密码至少需要 6 位。',
    authUsernameTaken: '用户名已被占用，请换一个。',
    authUsernameInvalid: '用户名需为 2-20 位字母、数字、下划线或短横线。',
    authLoginBadCredentials: '用户名或密码错误。',
    authEmailUnconfirmed: '账号尚未确认，请先在 Supabase 中关闭 Confirm email。',
    authCheckError: '查重失败',
    authOperationError: '操作失败',
    navCampaign: '法庭闯关',
    navForge: '案件工坊',
    navAudit: '合同猎魔',
    navCommunity: '社区广场',
    commonReload: '重新加载',
    commonRequired: '必填',
    forgeBadge: 'P0 · 案件配置',
    forgeIntro: '输入一个真实争议概念，系统会先生成可编辑的训练草案。原始材料、金额和待核验事项不会被示例文本覆盖。',
    forgeConcept: '案件概念',
    forgeDefaultConcept: '租客退房时，房东以墙面划痕为由扣留押金3000元，但划痕在入住前已存在。',
    forgePlaintiff: '原告',
    forgeDefendant: '被告',
    forgeSide: '代理立场',
    forgeJurisdiction: '管辖地区',
    forgePlaintiffOption: '原告',
    forgeDefendantOption: '被告',
    forgeOtherOption: '其他',
    forgeMainland: '中国大陆',
    forgeHongKong: '中国香港',
    forgeCrossBorder: '跨境示范',
    forgeMaterials: '材料接入（MVP）',
    forgeMaterialsHint: '可先粘贴原文；合同审查页支持 TXT / MD 文本文件。PDF、Word、图片解析接口保留在下一迭代。',
    forgeLoading: '正在配置案件…',
    forgeSubmit: '生成案件草案 →',
    forgeSpace: '案件空间',
    forgeConfigured: '已配置',
    forgeWaiting: '等待输入',
    forgeFocus: '争议焦点',
    forgeEvidencePlan: '建议先找的原件',
    forgeTrace: '可追溯状态',
    forgeSource: '来源：',
    forgeAmount: '金额：',
    forgePending: '待核验',
    forgeHumanConfirm: '需要人工确认',
    forgeEmpty: '案件草案会在这里生成，并可作为法庭闯关的事实底稿。',
    auditBadge: 'P1 · 多 Skill',
    auditIntro: '通用合同 Skill 先看完整性，专项 Skill 再看行业风险。每条意见都会返回命中的原文、Skill 版本、法律来源和待确认问题。',
    auditBackground: '合同背景',
    auditBackgroundPlaceholder: '交易目的、履行阶段、我方主要风险偏好…',
    auditPosition: '我方合同地位',
    auditType: '合同类型',
    auditOriginalFile: '原文文件',
    auditChooseFile: '选择 TXT / MD 原文',
    auditLoaded: '已载入：',
    auditReadableText: '请粘贴可读文本',
    auditReadFailed: '读取失败',
    auditLocalFile: '文件默认只在当前浏览器读取',
    auditText: '合同原文',
    auditLoadSample: '加载租赁示例',
    auditLoading: '正在逐条审查…',
    auditSubmit: '开始合同审查 →',
    auditResults: '风险图鉴 & 对照稿',
    auditFindings: '{count} 条发现',
    auditWaiting: '等待审查',
    auditClauses: '识别条款',
    auditRisks: '风险发现',
    auditHighRisk: '高风险',
    auditOurSide: '我方：',
    auditContractType: '类型：',
    auditCoverage: '来源覆盖：',
    auditEmpty: '审查结果会逐条对齐原文与修改方向，并显示可点击的法律来源。',
    communityBadge: '脱敏分享',
    communityWeekly: '本周训练榜',
    communityLearner: '案件训练者',
    communityPrivacy: '隐私 · 默认私有',
    communityPrivacyBody: '案件、合同和聊天记录不会自动公开。发布前请先脱敏，并确认内容不含个人信息。',
    communityShare: '分享一次复盘',
    communityTitle: '标题',
    communityTags: '标签',
    communityBody: '内容',
    communityTitlePlaceholder: '例如：租赁押金关卡的证据链',
    communityTagsPlaceholder: '#证据链 #租赁',
    communityBodyPlaceholder: '分享你的思路、遇到的质证或合同审查方法…',
    communityPrivacyCheck: '我已脱敏，并确认不发布合同、聊天记录等原始文件',
    communityPublishing: '正在发布…',
    communityPublish: '发布到社区 →',
    communityLoading: '正在加载社区动态…',
    communityComments: '评论',
    communityPrivacyError: '请确认内容已脱敏且不包含需要保密的原始文件。',
    communityPublishError: '发布失败',
    communityAuthor: '你',
    findingNecessity: '必要度',
    findingClause: '第',
    findingClauseSuffix: '段',
    findingRisk: '风险：',
    findingDirection: '方向：',
    findingSuggested: '修改参考文本',
    findingConfidence: '置信度',
    findingPending: '待确认：',
  },
  en: {
    brandTitle: 'Meow Court',
    brandSubtitle: 'Legal training platform',
    brandAlt: 'Meow Court lawyer cat',
    skipLink: 'Skip to main content',
    login: 'Log in / Sign up',
    loginHint: 'Username + password',
    editProfile: 'Signed in · click to edit avatar',
    logout: 'Log out',
    localeZh: '中文',
    localeEn: 'EN',
    campaignTitle: 'Courtroom Quest',
    campaignSubtitle: 'Evidence → Cards → Verdict',
    campaignLead: 'Search the scene, turn evidence into combo cards, and work through 20 standalone cases that scale from a simple deposit dispute to a comprehensive trial.',
    campaignTag: 'Evidence + trial',
    campaignOpen: 'All {count} levels open',
    campaignProgress: 'Completed {done}/{total}',
    campaignLoadingMap: 'Loading the map…',
    campaignLoadingCase: 'Loading the case…',
    campaignBack: 'Back to map',
    campaignRulesTitle: 'Mission',
    campaignRulesBody: 'Read the case and its dispute points, inspect the original materials freely, then choose the best evidence cards to enter trial, answer challenges, and request a verdict.',
    campaignLevelBadge: 'Goal',
    campaignStart: 'Start investigation →',
    campaignFocusLabel: 'Dispute focus',
    campaignInvestigate: 'Investigation',
    campaignCourt: 'Trial',
    campaignVerdict: 'Verdict',
    campaignSearchTitle: 'Scene search',
    campaignSearchBadge: 'Free search',
    campaignSearchLog: 'Investigation log',
    campaignSourceTitle: 'Original files · grouped with the current materials',
    campaignSourceReader: 'Source reader',
    campaignSourceBadge: 'Original materials',
    campaignEvidenceTitle: 'Evidence deck',
    campaignEvidenceBadge: 'Selected {selected}/{total}',
    campaignEnterCourt: 'Enter trial with {count} evidence cards →',
    campaignChooseEvidence: 'Select evidence cards →',
    campaignInvestigateHint: 'Click the scene hotspots on the left, or click clues in the materials, and the collected evidence will appear here.',
    campaignCourtEntryHint: 'Choose up to {total} evidence cards. Pick by strength and relevance; shield and stamina recovery cards remain available.',
    campaignCourtRule: 'Recovery and shield cards come from tactical plays. Shields absorb counterattacks first. If you are out of attack cards, the draw prioritizes usable cards.',
    campaignDifficulty: 'Difficulty',
    campaignKeyEvidenceCount: 'key exhibits',
    campaignCollected: 'Collected',
    campaignKeyEvidence: 'Key evidence',
    campaignScore: 'Score',
    campaignReturnRetry: 'Return to investigation',
    campaignVictory: 'Victory!',
    campaignDefeat: 'Defeat',
    campaignRequestVerdict: 'Request verdict',
    campaignVerdictReady: 'You can request a verdict once the opponent HP reaches zero',
    campaignNext: 'Next level →',
    campaignFound: 'Found evidence',
    campaignRemoved: 'Removed evidence',
    campaignRemovedFromTrial: 'Removed from trial',
    campaignNewEvidence: 'new evidence',
    campaignEvidenceFallback: 'evidence',
    campaignExplore: 'Explore',
    campaignCollectedMark: 'Collected ✓',
    campaignOpenOriginal: 'Open full original →',
    campaignSelectedRemove: '✓ Selected · click to remove',
    campaignSelectTrial: 'Click to select for trial',
    campaignLevel: 'Level',
    campaignLevelEn: 'Level',
    campaignDifficultyInline: '· Difficulty',
    campaignScoreLabel: 'Score',
    courtOpponentHp: 'Opponent HP',
    courtPlayerHp: 'Our HP',
    courtStamina: 'Stamina',
    courtShield: 'Shield',
    courtRound: 'Trial round',
    courtWaiting: 'Waiting for the reply',
    courtTurnPlayer: 'Our turn',
    courtTurnOpponent: 'Opponent counterattacks',
    courtTurnPreparing: 'Opponent is preparing to counterattack…',
    courtTurnEnd: 'Round over',
    courtReturnMap: '← Back to map',
    courtInvestigate: 'Investigation',
    courtTrial: 'Card trial',
    courtVerdict: 'Verdict',
    courtOurSide: 'Our side',
    courtTheirSide: 'Opponent',
    courtEvidencePlay: 'Evidence card',
    courtRecoveryPlay: 'Recovery card',
    courtDefensePlay: 'Defense card',
    courtCost: 'Cost {cost} stamina',
    courtEffect: 'Effect:',
    courtSeconds: 'sec',
    courtHand: 'Hand {count}/{total} · draw a replacement after each play',
    courtPlayed: '{count} played · Stamina {stamina}/{max}',
    courtShieldAria: 'Shield {current}/{max}',
    courtEvidenceAccuracy: 'Credibility {score}/10',
    courtBattleFeedback: 'Waiting for trial feedback…',
    courtVerdictLocked: 'Request a verdict when the opponent HP reaches zero',
    courtEvidenceKey: 'Key evidence',
    courtEvidenceSupport: 'Supporting evidence',
    courtAction: 'Tactical action · not admissible as verdict evidence',
    courtPlayHint: 'Play a card · spend stamina and attack',
    courtRecoveryHint: 'Restores stamina · the opponent still counterattacks',
    courtDefenseHint: 'Grants shield · the opponent still counterattacks',
    courtRecoveryFull: 'Stamina full · unavailable',
    courtShieldFull: 'Shield full · unavailable',
    courtLowStamina: 'Not enough stamina · need {cost} more',
    courtBattleResultWin: 'The opponent HP hit zero first. The evidence chain worked. You can request a verdict now.',
    courtBattleResultLoss: 'Our HP hit zero first. The final verdict follows the game result; the evidence chain only shows the round.',
    courtBattleOver: 'Round over',
    courtJudgePrompt: 'Judge note:',
    courtOpponentReply: 'Opponent reply',
    courtPlayerStatement: 'Our statement',
    courtOpponentReplyPending: 'Opponent is drafting a reply…',
    courtNoDebate: 'Check stamina first, then choose an evidence card to play. After each play, a new card is drawn; use recovery cards when stamina runs low.',
    courtEvidenceChain: 'Evidence chain',
    courtLegalLeads: 'Legal research leads',
    courtReady: 'The key evidence chain is complete. You can request a training verdict.',
    briefTitle: 'Goal',
    briefStart: 'Start investigation →',
    profileTitleNew: 'Create player profile',
    profileTitleEdit: 'Edit player profile',
    profileDesc: 'Set a nickname and avatar to start tracking your runs.',
    profileNameLabel: 'Username / nickname',
    profileNameHelpAuthed: 'Account name',
    profileNameHelpRequired: 'Required',
    profileAvatarTitle: 'Choose avatar',
    profileAvatarHint: 'Use an existing cat character',
    profilePrivacy: 'The username is used for login and leaderboard deduplication. The password goes only to Supabase Auth and is not written to the profile table.',
    profileSave: 'Save and start',
    profileLater: 'Maybe later',
    profileAuthLink: 'Sign up / log in (sync progress across devices)',
    profileClose: 'Close profile card',
    profileMissingName: 'Complete player profile',
    profileInvalidName: 'Username must be 2-20 letters, numbers, underscores, or hyphens.',
    profileSaveError: 'Could not save. Please try again.',
    profileSavedLocal: 'Saved locally; cloud sync will start after Supabase is configured.',
    profileCloudUnavailable: 'Cloud profile is temporarily unavailable; local mode is still ready.',
    profileRunSavedLocal: 'This run was saved locally; cloud sync will start after Supabase is configured.',
    logoutError: 'Could not log out',
    authTitleRegister: 'Create player account',
    authTitleLogin: 'Log in to player account',
    authDesc: 'Your username is your nickname; no email required.',
    authRegister: 'Sign up',
    authLogin: 'Log in',
    authNameLabel: 'Username / nickname',
    authNameHelp: '2-20 chars',
    authPasswordLabel: 'Password',
    authPasswordHelp: 'At least 6 chars',
    authConfirmLabel: 'Confirm password',
    authConfirmHelp: 'Type again',
    authUsernameChecking: 'Checking…',
    authUsernameAvailable: 'Available ✓',
    authCheck: 'Check',
    authSubmitRegister: 'Sign up and start →',
    authSubmitLogin: 'Log in →',
    authClose: 'Close login window',
    authRegisterMessage: 'Sign-up succeeded, but email confirmation is still enabled. Disable Confirm email in Supabase Auth → Providers, then log in again.',
    authNotConfigured: 'Supabase is not configured yet, so this build can only run locally for now.',
    authPasswordMismatch: 'The two passwords do not match.',
    authPasswordShort: 'Password must be at least 6 characters.',
    authUsernameTaken: 'That username is already taken. Try another one.',
    authUsernameInvalid: 'Username must be 2-20 letters, numbers, underscores, or hyphens.',
    authLoginBadCredentials: 'Username or password is incorrect.',
    authEmailUnconfirmed: 'The account is not confirmed yet. Turn off Confirm email in Supabase first.',
    authCheckError: 'Could not check username',
    authOperationError: 'Something went wrong',
    navCampaign: 'Courtroom Quest',
    navForge: 'Case Forge',
    navAudit: 'Contract Hunt',
    navCommunity: 'Community',
    commonReload: 'Reload',
    commonRequired: 'Required',
    forgeBadge: 'P0 · Case setup',
    forgeIntro: 'Describe a real dispute and the system will generate an editable training draft. Original materials, amounts, and verification items stay intact.',
    forgeConcept: 'Case concept',
    forgeDefaultConcept: 'A landlord withholds a ¥3,000 deposit for wall scratches that were already present before move-in.',
    forgePlaintiff: 'Plaintiff',
    forgeDefendant: 'Defendant',
    forgeSide: 'Our role',
    forgeJurisdiction: 'Jurisdiction',
    forgePlaintiffOption: 'Plaintiff',
    forgeDefendantOption: 'Defendant',
    forgeOtherOption: 'Other',
    forgeMainland: 'Mainland China',
    forgeHongKong: 'Hong Kong',
    forgeCrossBorder: 'Cross-border demo',
    forgeMaterials: 'Materials intake (MVP)',
    forgeMaterialsHint: 'Paste source text for now; contract review accepts TXT / MD files. PDF, Word, and image parsing are reserved for a later iteration.',
    forgeLoading: 'Preparing case…',
    forgeSubmit: 'Generate case draft →',
    forgeSpace: 'Case space',
    forgeConfigured: 'Configured',
    forgeWaiting: 'Waiting for input',
    forgeFocus: 'Dispute focus',
    forgeEvidencePlan: 'Suggested exhibits',
    forgeTrace: 'Traceability',
    forgeSource: 'Source: ',
    forgeAmount: 'Amount: ',
    forgePending: 'Pending verification',
    forgeHumanConfirm: 'Manual confirmation required',
    forgeEmpty: 'The generated case draft will appear here as the factual basis for a courtroom quest.',
    auditBadge: 'P1 · Multi-skill',
    auditIntro: 'The general contract skill checks completeness first, then specialist skills review industry risks. Each finding returns the matched text, skill version, legal sources, and open questions.',
    auditBackground: 'Contract background',
    auditBackgroundPlaceholder: 'Transaction purpose, performance stage, and our main risk preferences…',
    auditPosition: 'Our contract position',
    auditType: 'Contract type',
    auditOriginalFile: 'Source file',
    auditChooseFile: 'Choose TXT / MD source',
    auditLoaded: 'Loaded: ',
    auditReadableText: 'paste readable text',
    auditReadFailed: 'read failed',
    auditLocalFile: 'Files are read only in this browser',
    auditText: 'Contract text',
    auditLoadSample: 'Load lease sample',
    auditLoading: 'Reviewing clause by clause…',
    auditSubmit: 'Start contract review →',
    auditResults: 'Risk atlas & redline',
    auditFindings: '{count} findings',
    auditWaiting: 'Waiting for review',
    auditClauses: 'Clauses',
    auditRisks: 'Findings',
    auditHighRisk: 'High risk',
    auditOurSide: 'Our side: ',
    auditContractType: 'Type: ',
    auditCoverage: 'Source coverage: ',
    auditEmpty: 'Review results align each finding with source text and revision direction, with clickable legal sources.',
    communityBadge: 'Redacted sharing',
    communityWeekly: 'Weekly training leaderboard',
    communityLearner: 'Case learner',
    communityPrivacy: 'Privacy · private by default',
    communityPrivacyBody: 'Cases, contracts, and chats are never public automatically. Redact before posting and confirm there is no personal information.',
    communityShare: 'Share a debrief',
    communityTitle: 'Title',
    communityTags: 'Tags',
    communityBody: 'Body',
    communityTitlePlaceholder: 'e.g. Evidence chain for the rental-deposit level',
    communityTagsPlaceholder: '#evidence #lease',
    communityBodyPlaceholder: 'Share your reasoning, cross-examination notes, or contract-review method…',
    communityPrivacyCheck: 'I redacted this and confirm I am not posting original contracts or chats',
    communityPublishing: 'Publishing…',
    communityPublish: 'Post to community →',
    communityLoading: 'Loading community feed…',
    communityComments: 'Comments',
    communityPrivacyError: 'Confirm that the post is redacted and contains no confidential originals.',
    communityPublishError: 'Could not publish',
    communityAuthor: 'You',
    findingNecessity: 'Necessity',
    findingClause: 'Clause ',
    findingClauseSuffix: '',
    findingRisk: 'Risk: ',
    findingDirection: 'Direction: ',
    findingSuggested: 'Suggested revision',
    findingConfidence: 'Confidence',
    findingPending: 'Open questions: ',
  },
} as const;

type LevelCopy = { title: string; desc: string };

const LEVEL_COPY: Record<Locale, Record<number, LevelCopy>> = {
  zh: {
    1: { title: '押金猎人', desc: '租房押金纠纷' },
    2: { title: '七天无理由', desc: '电商退货争议' },
    3: { title: '加班费幽灵', desc: '劳动仲裁入门' },
    4: { title: '信息饕餮', desc: '隐私政策漏洞' },
    5: { title: '版权窃贼', desc: '用户协议陷阱' },
    6: { title: '竞业锁链', desc: '离职限制条款' },
    7: { title: '格式条款恶魔', desc: '霸王条款识别' },
    8: { title: '仲裁迷宫', desc: '仲裁程序争议' },
    9: { title: '证据湮灭', desc: '举证责任翻转' },
    10: { title: '终极审判', desc: '综合大案' },
    11: { title: '租赁押金争议', desc: '房屋租赁合同纠纷' },
    12: { title: '网购退货之争', desc: '网络购物合同纠纷' },
    13: { title: '离职工资之争', desc: '劳动争议' },
    14: { title: '购房尾款之争', desc: '房屋买卖合同纠纷' },
    15: { title: '转账之争', desc: '民间借贷纠纷' },
    16: { title: '装修停工之争', desc: '承揽/装饰装修合同纠纷' },
    17: { title: '二手车之争', desc: '买卖合同纠纷' },
    18: { title: '验收之争', desc: '买卖合同纠纷' },
    19: { title: '理赔之争', desc: '保险合同纠纷' },
    20: { title: '酒局之后', desc: '生命权、健康权、身体权纠纷' },
  },
  en: {
    1: { title: 'Deposit Hunter', desc: 'Lease deposit dispute' },
    2: { title: 'No-Reason Return', desc: 'E-commerce return dispute' },
    3: { title: 'Overtime Ghost', desc: 'Labor arbitration primer' },
    4: { title: 'Data Glutton', desc: 'Privacy policy loophole' },
    5: { title: 'Copyright Thief', desc: 'User-agreement trap' },
    6: { title: 'Non-Compete Chain', desc: 'Departure restriction clause' },
    7: { title: 'Boilerplate Demon', desc: 'Unfair-term spotter' },
    8: { title: 'Arbitration Maze', desc: 'Arbitration procedure dispute' },
    9: { title: 'Evidence Gone Missing', desc: 'Burden-shifting dispute' },
    10: { title: 'Final Trial', desc: 'Comprehensive case' },
    11: { title: 'Rental Deposit Dispute', desc: 'Lease contract dispute' },
    12: { title: 'Online Return Dispute', desc: 'E-commerce purchase dispute' },
    13: { title: 'Wage Dispute After Resignation', desc: 'Labor dispute' },
    14: { title: 'Home Purchase Balance Dispute', desc: 'Housing-sale contract dispute' },
    15: { title: 'Transfer Dispute', desc: 'Private lending dispute' },
    16: { title: 'Renovation Stoppage Dispute', desc: 'Renovation contract dispute' },
    17: { title: 'Used-Car Dispute', desc: 'Sales contract dispute' },
    18: { title: 'Acceptance Dispute', desc: 'Sales contract dispute' },
    19: { title: 'Claim Dispute', desc: 'Insurance contract dispute' },
    20: { title: 'After the Drinking Party', desc: 'Life, health, and bodily-rights dispute' },
  },
};

// The campaign API keeps the authoritative source text in Chinese. These
// presentation translations cover the text shown around each exhibit while
// preserving the original material itself for the source-reader details view.
const CASE_TEXT_COPY: Record<string, string> = {
  '胡某购买899元普通手提包，2026年8月14日签收，8月17日申请退货。商家援引商品页“不支持七天无理由退货”拒绝退款。': 'Hu bought a ¥899 ordinary handbag, received it on Aug 14, 2026, and requested a return on Aug 17. The merchant refused, citing a product-page notice that said “no seven-day no-reason returns.”',
  '证明商品不属于法定退货例外、申请未超期且商品完好，回应商家的页面免责提示。': 'Show that the item is not a statutory return exception, the request was timely, and the item remained intact; answer the merchant’s disclaimer.',
  '普通手提包是否属于退货例外': 'Whether an ordinary handbag is a statutory return exception',
  '签收与申请是否相隔七日以内': 'Whether the request was made within seven days of receipt',
  '拆封检查是否影响商品完好': 'Whether opening the package affected the item’s condition',
  '场景一 · 购物订单': 'Scene 1 · Purchase order',
  '场景二 · 快递与售后': 'Scene 2 · Delivery & after-sales',
  '场景三 · 开箱桌': 'Scene 3 · Unboxing desk',
  '对照商品性质、支付金额和商品页面的退货提示。': 'Check the item type, payment amount, and the return notice on the product page.',
  '从物流签收、退款申请和客服对话还原时间线。': 'Reconstruct the timeline from delivery, the refund request, and customer-service chats.',
  '检查连续开箱视频中的吊牌、包装和使用痕迹。': 'Check the tags, packaging, and signs of use in the continuous unboxing video.',
  '商品订单与页面提示': 'Product order & page notice',
  '签收与售后时间线': 'Receipt & after-sales timeline',
  '商家拒绝退货记录': 'Merchant refusal record',
  '开箱与商品状态视频': 'Unboxing & item-condition video',
  '899元普通手提包，页面单方标注不支持退货。': 'A ¥899 ordinary handbag; the page unilaterally stated that returns were not supported.',
  '8月14日签收，8月17日提出退货申请。': 'Received Aug 14 and requested a return Aug 17.',
  '商家仅以页面提示和“特殊商品”为由拒绝。': 'The merchant refused only by citing the page notice and “special goods.”',
  '吊牌、配件和包装齐全，未见使用痕迹。': 'Tags, accessories, and packaging were complete, with no signs of use.',
  '证明商品性质、价款及商家排除退货的依据。': 'Establish the item type, price, and the merchant’s basis for excluding returns.',
  '证明消费者在收货后七日内提出退货。': 'Establish that the consumer requested a return within seven days of receipt.',
  '核对经营者是否证明了法定退货例外。': 'Check whether the merchant proved a statutory return exception.',
  '证明仅作合理拆封检查且退货时商品保持完好。': 'Establish that the package was opened only for reasonable inspection and the item remained intact on return.',
  '商品订单20260811001': 'Product order 20260811001',
  '下单：': 'Order placed: ',
  '女士手提包 ×1；实付899元；非定制、非鲜活易腐商品。': 'Women’s handbag ×1; paid ¥899; not customized, fresh, or perishable.',
  '商品页面售后说明：本商品不支持七天无理由退货。': 'Product-page after-sales note: This item does not support seven-day no-reason returns.',
  '无按消费者要求定制或改变商品的记录。': 'No record shows that the item was customized or altered at the consumer’s request.',
  '物流签收：': 'Delivery received: ',
  '签收人胡某。': 'Recipient: Hu.',
  '售后申请：': 'After-sales request: ',
  '申请原因：不喜欢/不合适；申请退款899元。': 'Reason: disliked / unsuitable; refund requested: ¥899.',
  '售后系统已受理，商家于当天拒绝。': 'The after-sales system accepted the request; the merchant refused it the same day.',
  '客服：特殊商品，售出不退。': 'Support: Special goods; no returns after sale.',
  '胡某：这不是定制商品，吊牌还在，为什么特殊？': 'Hu: This is not customized, and the tag is still attached. Why is it “special”?',
  '客服：页面写了不支持，你下单就是同意。': 'Support: The page said returns were not supported; placing the order means you agreed.',
  '商家未补充商品不宜退货的具体性质说明。': 'The merchant gave no specific explanation of why the item could not legally be returned.',
  '证明损坏形成时间早于租客退租。': 'Establish that the damage existed before move-out.',
};

const GENERIC_CASE_REPLACEMENTS: Array<[RegExp, string]> = [
  [/【虚构训练材料】/g, '[Fictional training material]'], [/虚构训练材料/g, 'fictional training material'],
  [/^下单：/g, 'Order placed: '], [/^物流签收：/g, 'Delivery received: '], [/^售后申请：/g, 'After-sales request: '],
  [/^形成时间：/g, 'Created: '], [/^拍摄位置：/g, 'Location: '], [/^可见：/g, 'Visible: '], [/^支付记录：/g, 'Payment record: '],
  [/^申请原因：/g, 'Reason: '], [/^实付/g, 'Paid'], [/^金额/g, 'Amount'],
  [/张某/g, 'Zhang'], [/李某/g, 'Li'], [/胡某/g, 'Hu'], [/王某/g, 'Wang'], [/林某/g, 'Lin'], [/陈某/g, 'Chen'], [/周某/g, 'Zhou'], [/赵某/g, 'Zhao'], [/吴某/g, 'Wu'], [/许某/g, 'Xu'],
  [/主管/g, 'Supervisor'], [/公司/g, 'Company'], [/平台/g, 'Platform'], [/运营商/g, 'Operator'], [/经营者/g, 'Merchant'],
  [/^场景一\s*·\s*/, 'Scene 1 · '], [/^场景二\s*·\s*/, 'Scene 2 · '], [/^场景三\s*·\s*/, 'Scene 3 · '],
  [/^场景四\s*·\s*/, 'Scene 4 · '], [/^原告\s*·\s*/, 'Plaintiff · '], [/^被告\s*·\s*/, 'Defendant · '],
  [/^申请人\s*·\s*/, 'Applicant · '], [/^被申请人\s*·\s*/, 'Respondent · '],
  [/证据定位：/g, 'Evidence pointer: '], [/证据链/g, 'evidence chain'], [/关键证据/g, 'key evidence'], [/补充证据/g, 'supporting evidence'],
  [/商品订单/g, 'Product order'], [/页面提示/g, 'page notice'], [/签收/g, 'receipt'], [/退货/g, 'return'], [/退款/g, 'refund'],
  [/商家/g, 'merchant'], [/消费者/g, 'consumer'], [/客服/g, 'support'], [/场景/g, 'scene'], [/原始材料/g, 'original materials'],
  [/房东/g, 'landlord'], [/租客/g, 'tenant'], [/合同/g, 'contract'], [/押金/g, 'deposit'], [/维修/g, 'repair'],
  [/证明/g, 'Establish '], [/核对/g, 'Check '], [/审查/g, 'Review '], [/争议/g, 'dispute'], [/请求/g, 'request'],
  [/金额/g, 'amount'], [/记录/g, 'record'], [/时间线/g, 'timeline'], [/申请/g, 'request'], [/同意/g, 'consent'], [/撤回/g, 'withdrawal'],
  [/删除/g, 'deletion'], [/通知/g, 'notice'], [/支付/g, 'payment'], [/原件/g, 'original exhibit'], [/材料/g, 'material'],
  [/对方代理人：/g, 'Opposing counsel: '], [/已收到/g, 'Received '], [/当前未出示有效的本关证据，不能以其他案件的材料替代举证。/g, 'No valid exhibit from this case has been shown; material from another case cannot substitute for proof.'],
  [/关于/g, 'Regarding '], [/目前只是单方陈述，请提交能定位到原件的本案证据。/g, 'this is currently only a one-sided statement; submit an exhibit from this case that can be located in the source materials.'],
  [/本轮围绕/g, 'This round concerns '], [/已关联(\d+)项争点。/g, 'Linked $1 dispute point(s).'], [/论点尚未具体回应本案争点。/g, 'The argument does not yet address this case’s dispute point.'],
  [/尚缺关键材料：/g, 'Missing key materials: '], [/关键材料已齐备，仍须解释其与请求的关联及证明力。/g, 'Key materials are complete; explain their link to the claim and their evidentiary weight.'],
  [/请继续围绕/g, 'Continue by addressing '], [/补充原件和论证。/g, ' with exhibits and reasoning.'],
  [/（本局胜诉）/g, ' (won this round)'], [/训练裁决：/g, 'Training verdict: '], [/本局游戏结果判定/g, 'the game result finds that '], [/的请求不获支持/g, '’s claim is not supported'],
  [/本局游戏结果显示对方先取得胜利。/g, 'The game result shows that the opponent won first.'], [/最终裁决依据本局游戏结果，而不是证据是否齐全；证据链仅用于展示本局的举证过程。/g, 'The final verdict follows the game result, not whether the evidence is complete; the evidence chain only shows the round’s proof process.'],
  [/尚无可核验的本关关键证据/g, 'No verifiable key exhibit from this case yet'], [/虚构案件的规则化训练反馈，不是真实法院或仲裁机构裁决，不构成法律意见。/g, 'Rule-based training feedback for a fictional case; not a real court or arbitral decision and not legal advice.'],
  [/：/g, ': '],
];

export function translateCaseText(value: string, locale: Locale, fallback = 'Case material') {
  if (locale === 'zh' || !value) return value;
  if (CASE_TEXT_COPY[value]) return CASE_TEXT_COPY[value];
  const translated = value.split('\n').map((line) => CASE_TEXT_COPY[line] || GENERIC_CASE_REPLACEMENTS.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), line)).join('\n');
  return /[\u3400-\u9fff]/.test(translated) ? fallback : translated;
}

const TYPE_COPY: Record<string, Record<Locale, string>> = {
  '房屋租赁合同纠纷': { zh: '房屋租赁合同纠纷', en: 'Lease contract dispute' },
  '网络消费合同纠纷': { zh: '网络消费合同纠纷', en: 'E-commerce consumer dispute' },
  '劳动争议': { zh: '劳动争议', en: 'Labor dispute' },
  '个人信息保护纠纷': { zh: '个人信息保护纠纷', en: 'Personal information dispute' },
  '著作权许可使用纠纷': { zh: '著作权许可使用纠纷', en: 'Copyright license dispute' },
  '预付式消费合同纠纷': { zh: '预付式消费合同纠纷', en: 'Prepaid consumer dispute' },
  '仲裁司法审查训练': { zh: '仲裁司法审查训练', en: 'Arbitration judicial review exercise' },
  '劳动争议 · 举证妨碍': { zh: '劳动争议 · 举证妨碍', en: 'Labor dispute · evidence obstruction' },
  '技术服务合同及知识产权、个人信息综合争议': { zh: '技术服务合同及知识产权、个人信息综合争议', en: 'Tech services, IP, and personal-data dispute' },
  '网络购物合同纠纷': { zh: '网络购物合同纠纷', en: 'Online shopping contract dispute' },
  '房屋买卖合同纠纷': { zh: '房屋买卖合同纠纷', en: 'Housing-sale contract dispute' },
  '民间借贷纠纷': { zh: '民间借贷纠纷', en: 'Private lending dispute' },
  '承揽/装饰装修合同纠纷': { zh: '承揽/装饰装修合同纠纷', en: 'Contracting / renovation dispute' },
  '买卖合同纠纷': { zh: '买卖合同纠纷', en: 'Sales contract dispute' },
  '保险合同纠纷': { zh: '保险合同纠纷', en: 'Insurance contract dispute' },
  '生命权、健康权、身体权纠纷': { zh: '生命权、健康权、身体权纠纷', en: 'Life, health, and bodily-rights dispute' },
};

const EVIDENCE_NATURE_COPY: Record<string, Record<Locale, string>> = {
  书证: { zh: '书证', en: 'Documentary evidence' },
  影像物证: { zh: '影像物证', en: 'Visual evidence' },
  支付凭证: { zh: '支付凭证', en: 'Payment proof' },
  单据: { zh: '单据', en: 'Receipt' },
  对话记录: { zh: '对话记录', en: 'Chat log' },
  其他材料: { zh: '其他材料', en: 'Other material' },
  体力恢复: { zh: '体力恢复', en: 'Stamina recovery' },
  防御策略: { zh: '防御策略', en: 'Defense tactic' },
};

const TACTICAL_CARD_COPY: Record<string, { name: Record<Locale, string>; nature: Record<Locale, string>; effect: Record<Locale, string> }> = {
  'recover-breath': { name: { zh: '深呼吸', en: 'Take a breath' }, nature: { zh: '体力恢复', en: 'Stamina recovery' }, effect: { zh: '恢复 3 点体力 · 不造成伤害', en: 'Restore 3 stamina · no damage' } },
  'recover-organize': { name: { zh: '整理思路', en: 'Organize thoughts' }, nature: { zh: '体力恢复', en: 'Stamina recovery' }, effect: { zh: '消耗后恢复 5 点体力 · 净恢复最多 4 点', en: 'Spend 1, restore 5 stamina · net gain up to 4' } },
  'shield-pause': { name: { zh: '请求缓冲', en: 'Request a pause' }, nature: { zh: '防御策略', en: 'Defense tactic' }, effect: { zh: '获得 5 点护盾 · 抵挡后续反击', en: 'Gain 5 shield · block the next counterattack' } },
  'shield-seal': { name: { zh: '封存原件', en: 'Seal the exhibit' }, nature: { zh: '防御策略', en: 'Defense tactic' }, effect: { zh: '获得 8 点护盾 · 抵挡后续反击', en: 'Gain 8 shield · block the next counterattack' } },
};

const BATTLE_EFFECT_COPY: Array<[RegExp, (match: RegExpMatchArray) => Record<Locale, string>]> = [
  [/^护盾 \+(\d+)$/, (match) => ({ zh: `护盾 +${match[1]}`, en: `Shield +${match[1]}` })],
  [/^体力 \+(\d+)$/, (match) => ({ zh: `体力 +${match[1]}`, en: `Stamina +${match[1]}` })],
  [/^异议！-(\d+)$/, (match) => ({ zh: `异议！-${match[1]}`, en: `Objection! -${match[1]}` })],
  [/^护盾吸收 (\d+) · 受伤 -(\d+)$/, (match) => ({ zh: `护盾吸收 ${match[1]} · 受伤 -${match[2]}`, en: `Shield absorbs ${match[1]} · Takes ${match[2]}` })],
  [/^护盾吸收 (\d+) · 完全抵挡$/, (match) => ({ zh: `护盾吸收 ${match[1]} · 完全抵挡`, en: `Shield absorbs ${match[1]} · Fully blocked` })],
  [/^(超时反击|反击！) -(\d+)$/, (match) => ({ zh: `${match[1]} -${match[2]}`, en: `${match[1] === '超时反击' ? 'Timeout counterattack' : 'Counterattack!'} -${match[2]}` })],
];

export function getAppCopy(locale: Locale) {
  return APP_COPY[locale];
}

export function getLevelCopy(levelId: number, locale: Locale, fallback?: { title: string; desc: string }) {
  const entry = LEVEL_COPY[locale][levelId];
  if (entry) return { ...entry, desc: stripCampaignPrefix(entry.desc) };
  return {
    title: stripCampaignPrefix(fallback?.title || ''),
    desc: stripCampaignPrefix(fallback?.desc || ''),
  };
}

export function getTypeCopy(type: string, locale: Locale) {
  return TYPE_COPY[type]?.[locale] || type;
}

export function getEvidenceNatureCopy(type: string, locale: Locale) {
  return EVIDENCE_NATURE_COPY[type]?.[locale] || EVIDENCE_NATURE_COPY['其他材料'][locale];
}

export function getBattleEffectCopy(label: string, locale: Locale) {
  for (const [pattern, formatter] of BATTLE_EFFECT_COPY) {
    const match = label.match(pattern);
    if (match) return formatter(match)[locale];
  }
  return label;
}

export function getTacticalCardCopy(id: string, locale: Locale) {
  const entry = TACTICAL_CARD_COPY[id];
  return entry ? { name: entry.name[locale], nature: entry.nature[locale], effect: entry.effect[locale] } : null;
}

export function translatePartyLabel(value: string, locale: Locale) {
  if (locale === 'zh') return value;
  const replacements: Array<[RegExp, string]> = [
    [/^原告\s*·\s*/, 'Plaintiff · '],
    [/^被告\s*·\s*/, 'Defendant · '],
    [/^申请人\s*·\s*/, 'Applicant · '],
    [/^被申请人\s*·\s*/, 'Respondent · '],
    [/^消费者/, 'Consumer '],
    [/^租客/, 'Tenant '],
    [/^房东/, 'Landlord '],
    [/^前员工/, 'Former employee '],
    [/^员工/, 'Employee '],
    [/^买家/, 'Buyer '],
    [/^买受人/, 'Buyer '],
    [/^出借人/, 'Lender '],
    [/^收款人/, 'Recipient '],
    [/^业主/, 'Owner '],
    [/^购车人/, 'Car buyer '],
    [/^采购方/, 'Purchaser '],
    [/^供应商/, 'Supplier '],
    [/^投保人\/受益人/, 'Policyholder / beneficiary '],
    [/^死者家属/, 'Family of the deceased '],
    [/^同桌组织者与劝酒者/, 'Host and drink-pushers '],
    [/^门店经营者/, 'Store operator '],
    [/^数字服务公司/, 'Digital services company '],
    [/^科技公司/, 'Tech company '],
  ];
  let result = value;
  for (const [pattern, replacement] of replacements) result = result.replace(pattern, replacement);
  result = result
    .replace(/张某/g, 'Zhang').replace(/李某/g, 'Li').replace(/胡某/g, 'Hu').replace(/王某/g, 'Wang')
    .replace(/林某/g, 'Lin').replace(/陈某/g, 'Chen').replace(/周某/g, 'Zhou').replace(/赵某/g, 'Zhao')
    .replace(/吴某/g, 'Wu').replace(/许某/g, 'Xu').replace(/设备采购公司/g, 'Equipment buyer')
    .replace(/设备供应商/g, 'Equipment supplier').replace(/门店经营者/g, 'Store operator');
  result = result.replace(/租客/g, 'Tenant ').replace(/房东/g, 'Landlord ').replace(/消费者/g, 'Consumer ')
    .replace(/员工/g, 'Employee ').replace(/用户/g, 'User ').replace(/插画师/g, 'Illustrator ')
    .replace(/手提包网店/g, 'Handbag store').replace(/记账应用运营商/g, 'Budget-app operator')
    .replace(/创作平台/g, 'Creative platform').replace(/健身公司/g, 'Fitness company')
    .replace(/[\u3400-\u9fff]/g, '');
  return result;
}
